#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dropdown options for Dataify Indeed company info collection."""

STATE_OPTIONS = [
    "United States",
    "Alabama - 60 companies",
    "Birmingham, AL - 17 companies",
    "Huntsville, AL - 10 companies",
    "Alaska - 15 companies",
    "Anchorage, AK - 12 companies",
    "Arizona - 82 companies",
    "Phoenix, AZ - 38 companies",
    "Scottsdale, AZ - 11 companies",
    "Tempe, AZ - 14 companies",
    "Tucson, AZ - 17 companies",
    "Arkansas - 31 companies",
    "California - 332 companies",
    "Fresno, CA - 10 companies",
    "Irvine, CA - 24 companies",
    "Long Beach, CA - 10 companies",
    "Los Angeles, CA - 52 companies",
    "Oakland, CA - 11 companies",
    "Ontario, CA - 11 companies",
    "Sacramento, CA - 23 companies",
    "San Diego, CA - 24 companies",
    "San Francisco Bay Area, CA - 16 companies",
    "San Francisco, CA - 38 companies",
    "San Jose, CA - 24 companies",
    "Colorado - 94 companies",
    "Colorado Springs, CO - 23 companies",
    "Denver, CO - 33 companies",
    "Connecticut - 40 companies",
    "Hartford, CT - 9 companies",
    "Delaware - 18 companies",
    "District of Columbia - 37 companies",
    "Washington, DC - 37 companies",
    "ENG - 15 companies",
    "Pennsylvania, ENG - 15 companies",
    "Florida - 212 companies",
    "Boca Raton, FL - 12 companies",
    "Clearwater, FL - 10 companies",
    "Fort Lauderdale, FL - 26 companies",
    "Jacksonville, FL - 27 companies",
    "Miami, FL - 31 companies",
    "Orlando, FL - 27 companies",
    "Tampa, FL - 33 companies",
    "West Palm Beach, FL - 10 companies",
    "Georgia - 141 companies",
    "Atlanta, GA - 53 companies",
    "Marietta, GA - 11 companies",
    "Guam - 7 companies",
    "Hawaii - 11 companies",
    "Idaho - 33 companies",
    "Illinois - 125 companies",
    "Chicago, IL - 59 companies",
    "Indiana - 72 companies",
    "Fort Wayne, IN - 13 companies",
    "Indianapolis, IN - 28 companies",
    "Iowa - 37 companies",
    "Kansas - 38 companies",
    "Wichita, KS - 12 companies",
    "Kentucky - 48 companies",
    "Louisville, KY - 23 companies",
    "Louisiana - 54 companies",
    "Baton Rouge, LA - 13 companies",
    "New Orleans, LA - 14 companies",
    "Maine - 18 companies",
    "Maryland - 82 companies",
    "Baltimore, MD - 22 companies",
    "Bethesda, MD - 12 companies",
    "Columbia, MD - 10 companies",
    "Rockville, MD - 10 companies",
    "Massachusetts - 80 companies",
    "Boston, MA - 29 companies",
    "Michigan - 88 companies",
    "Detroit, MI - 17 companies",
    "Grand Rapids, MI - 15 companies",
    "Minnesota - 45 companies",
    "Minneapolis, MN - 18 companies",
    "Mississippi - 25 companies",
    "Missouri - 73 companies",
    "Kansas City, MO - 14 companies",
    "St. Louis, MO - 28 companies",
    "Montana - 8 companies",
    "Nebraska - 20 companies",
    "Omaha, NE - 16 companies",
    "Nevada - 42 companies",
    "Las Vegas, NV - 30 companies",
    "New Hampshire - 17 companies",
    "New Jersey - 84 companies",
    "New Mexico - 23 companies",
    "Albuquerque, NM - 10 companies",
    "New York State - 206 companies",
    "Brooklyn, NY - 21 companies",
    "Buffalo, NY - 13 companies",
    "Manhattan, NY - 15 companies",
    "Melville, NY - 11 companies",
    "New York, NY - 109 companies",
    "Rochester, NY - 12 companies",
    "White Plains, NY - 9 companies",
    "North Carolina - 92 companies",
    "Charlotte, NC - 33 companies",
    "Raleigh, NC - 19 companies",
    "North Dakota - 9 companies",
    "Northern Mariana Islands - 2 companies",
    "Ohio - 108 companies",
    "Akron, OH - 11 companies",
    "Cincinnati, OH - 23 companies",
    "Cleveland, OH - 26 companies",
    "Columbus, OH - 25 companies",
    "Toledo, OH - 10 companies",
    "Oklahoma - 50 companies",
    "Oklahoma City, OK - 19 companies",
    "Tulsa, OK - 20 companies",
    "Oregon - 48 companies",
    "Portland, OR - 25 companies",
    "Pennsylvania - 123 companies",
    "Philadelphia, PA - 29 companies",
    "Pittsburgh, PA - 25 companies",
    "Puerto Rico - 24 companies",
    "San Juan, PR - 12 companies",
    "Rhode Island - 19 companies",
    "South Carolina - 49 companies",
    "Charleston, SC - 10 companies",
    "Columbia, SC - 16 companies",
    "Greenville, SC - 9 companies",
    "South Dakota - 12 companies",
    "Tennessee - 85 companies",
    "Chattanooga, TN - 12 companies",
    "Knoxville, TN - 13 companies",
    "Memphis, TN - 20 companies",
    "Nashville, TN - 28 companies",
    "Texas - 266 companies",
    "Austin, TX - 37 companies",
    "Dallas-Fort Worth, TX - 16 companies",
    "Dallas, TX - 64 companies",
    "El Paso, TX - 13 companies",
    "Fort Worth, TX - 27 companies",
    "Houston, TX - 78 companies",
    "Irving, TX - 11 companies",
    "Plano, TX - 13 companies",
    "San Antonio, TX - 33 companies",
    "Utah - 44 companies",
    "Salt Lake City, UT - 16 companies",
    "Vermont - 8 companies",
    "Virgin Islands - 4 companies",
    "Virginia - 102 companies",
    "Alexandria, VA - 15 companies",
    "Arlington, VA - 11 companies",
    "Norfolk, VA - 11 companies",
    "Richmond, VA - 20 companies",
    "Tysons Corner, VA - 11 companies",
    "Virginia Beach, VA - 11 companies",
    "Washington State - 77 companies",
    "Seattle, WA - 21 companies",
    "Vancouver, WA - 17 companies",
    "West Virginia - 30 companies",
    "Wisconsin - 47 companies",
    "Madison, WI - 13 companies",
    "Milwaukee, WI - 12 companies",
    "Wyoming - 14 companies",
]

INDUSTRY_OPTIONS = [
    "All",
    "Accounting & Tax",
    "Advertising & Public Relations",
    "Aerospace & Defense",
    "Agriculture",
    "Airlines,Airports & Air Transportation",
    "Ambulance & Medical Transportation",
    "Animal Production",
    "Architectural & Engineering Services",
    "Arts,Entertainment & Recreation",
    "Auctions & Galleries",
    "Automotive Parts & Accessories Stores",
    "Banking & Lending",
    "Bars & Nightclubs",
    "Beauty & Personal Accessories Stores",
    "Beauty & Wellness",
    "Biotechnology",
    "Broadcast Media",
    "Business Consulting",
    "Car & Truck Rental",
    "Catering & Food Service Contractors",
    "Chemical Manufacturing",
    "Civic & Social Services",
    "Colleges & Universities",
    "Commercial Equipment Services",
    "Commercial Printing",
    "Computer Hardware Development",
    "Construction",
    "Construction,Repair & Maintenance Services",
    "Consumer Electronics & Appliances Stores",
    "Consumer Product Manufacturing",
    "Convenience Stores",
    "Crop Production",
    "Culture & Entertainment",
    "Debt Relief",
    "Dental Clinics",
    "Department,Clothing & Shoe Stores",
    "Drug & Health Stores",
    "Education",
    "Education & Training Services",
    "Electronics Manufacturing",
    "Energy & Utilities",
    "Energy,Mining & Utilities",
    "Event Services",
    "Farm Support",
    "Film Production",
    "Financial Services",
    "Financial Transaction Processing",
    "Fishery",
    "Floral Nursery",
    "Food & Beverage Manufacturing",
    "Food & Beverage Stores",
    "Forestry,Logging & Timber Operations",
    "Gambling",
    "General Merchandise & Superstores",
    "General Repair & Maintenance",
    "Gift,Novelty & Souvenir Stores",
    "Government & Public Administration",
    "Grantmaking & Charitable Foundations",
    "Grocery Stores",
    "Health Care Products Manufacturing",
    "Healthcare",
    "Home Furniture & Housewares Stores",
    "Hospitals & Health Clinics",
    "Hotels & Resorts",
    "Hotels & Travel Accommodation",
    "HR Consulting",
    "Human Resources & Staffing",
    "Information Technology",
    "Information Technology Support Services",
    "Insurance",
    "Insurance Agencies & Brokerages",
    "Insurance Carriers",
    "Internet & Web Services",
    "Investment & Asset Management",
    "Laundry & Dry Cleaning",
    "Law Firms",
    "Legal",
    "Legal Services",
    "Machinery Manufacturing",
    "Management & Consulting",
    "Manufacturing",
    "Marine Transportation",
    "Media & Communication",
    "Media & Entertainment Stores",
    "Medical Testing & Clinical Laboratories",
    "Membership Organizations",
    "Metal & Mineral Manufacturing",
    "Mining & Metals",
    "Municipal Agencies",
    "Music & Sound Production",
    "National Agencies",
    "Nonprofit & NGO",
    "Nursing Care",
    "Office Supply & Copy Stores",
    "Parking & Valet",
    "Personal Consumer Services",
    "Pet & Pet Supplies Stores",
    "Pet Care & Veterinary",
    "Pharmaceutical",
    "Pharmaceutical & Biotechnology",
    "Photography",
    "Preschools & Child Care Services",
    "Primary & Secondary Schools",
    "Private Households",
    "Property Management",
    "Publishing",
    "Rail Transportation",
    "Real Estate",
    "Real Estate Agencies",
    "Recruiting",
    "Recruiting & Staffing",
    "Religious Institutions",
    "Research & Development",
    "Restaurants & Cafes",
    "Restaurants & Food Service",
    "Retail & Wholesale",
    "Security & Protective",
    "Shipping & Trucking",
    "Software Development",
    "Sporting Goods Stores",
    "Sports & Recreation",
    "Staffing",
    "State & Regional Agencies",
    "Stock Exchanges",
    "Taxi & Car Services",
    "Telecommunications",
    "Textile & Apparel Manufacturing",
    "Ticket Sales",
    "Toy & Hobby Stores",
    "Translation & Linguistic Services",
    "Transportation & Logistics",
    "Transportation Equipment Manufacturing",
    "Transportation Management",
    "Travel Agencies",
    "Vehicle Dealers",
    "Vehicle Repair & Maintenance",
    "Video Game Publishing",
    "Waste Management",
    "Wholesale",
    "Wood & Paper Manufacturing",
]
